### ISSUE TITLE
Misc - dtk-tools-malaria examples should work

### ISSUE THREAD

**Issue by braybaud** [InstituteforDiseaseModeling/dtk-tools-malaria#40]

**Comment by CWiswell-IDM** [comment]
Talk to @JoRussell-IDM about Malariatherapy (but should be pretty close). The remaining three here might need legwork.

Malariatherapy | Test, content
-- | --
Sahel SMC | Test, content
Cambodia forest | Test, content
Gridded spatial | Test, content

**Comment by Sv3tlana** [comment]
Merged. Closing.
