### ISSUE TITLE
Misc - Is Valid_Intervention_States still needed? - NO. Not needed.

### ISSUE THREAD

**Issue by braybaud** [InstituteforDiseaseModeling/dtk-tools-malaria#43]

**Comment by braybaud** [comment]
Malaria contact: @jgerardin

**Comment by Sv3tlana** [comment]
I also verified that this is not used with DanB.

**Comment by Sv3tlana** [comment]
Valid_Intervneiton_States is not in dtk-tools-malaria, but there is an example of using it in dtk-tools, which can be cleaned up/removed:
C:\GitHub\dtk-tools>findstr /smip "Valid_Intervention" *.*
dtk\generic\params.py
dtk\interventions\intervention_states.py
examples\example_iterative\config.json

**Comment by CWiswell-IDM** [comment]
Please PR into dtk-tools to clean up, remove this stuff. consult with @braybaud

**Comment by Sv3tlana** [comment]
Pull request created: https://github.com/InstituteforDiseaseModeling/dtk-tools/pull/1634
