### ISSUE TITLE
Workflow - Amelia's N-site setup for intervention testing

### ISSUE THREAD

**Issue by braybaud** [InstituteforDiseaseModeling/dtk-tools-malaria#49]

**Comment by Sv3tlana** [comment]
make a comment-heavy example.

**Comment by Sv3tlana** [comment]
https://github.com/InstituteforDiseaseModeling/dtk-tools-malaria/pull/77 Waiting on the pull request to close this.

**Comment by Sv3tlana** [comment]
Merged. Closing.
