### ISSUE TITLE
Malaria-Ongoing has intervention changes and needs to use its own generated CampaignClass and CampaignEnum

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/dtk-tools-malaria#62]
Generating the new CampaignClass.py and CampaignEnum.py based on the Malaria-Ongoing eradication.exe is easy, but how do we maintain it? Do we 
1)make a "Malaria-Ongoing-dtk-tools" branch that will need to be updated whenever dtk-tools is updated? 
2) have the users manually replace the generated files in the dtk-tools? 

Both of these are extra work. With the second one being a quicker/easier work-around, but then it would be one more step that the researchers will have to do and keep in mind.
"install dtk-tools, generate the new campaignclass/enum files and replace them in dtk tools". 

This will be the same issue for anyone trying to use an exe that has intervention changes with dtk-tools - they would have to generate the CampaignClass/Enum files, replace them and then update the interventions that need it.

**Comment by Sv3tlana** [comment]
this is a copy of https://github.com/InstituteforDiseaseModeling/dtk-tools/issues/1636 as this is a dtk-tools and dtk-tools-malaria compatibility issue.

**Comment by devclinton** [comment]
Will resolve later
