### ISSUE TITLE
Interventions - code clean up. 

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/dtk-tools-malaria#67]
- [x] switch argument "nodes" which right now takes the NodeSet dictionary to nodeIDs, which takes a list of nodes to be in line with dtk-tools (and it'll be easier to use)
- [x] add google-style comments to all the functions
- [x] add defaults to all the functions 
- [x] add variable type to arguments in functions 
- [x] add disqualifying_properties

**Comment by CWiswell-IDM** [comment]
[] this is a checkbox

**Comment by Sv3tlana** [comment]
The work has been done, waiting on a pull request to be completed: https://github.com/InstituteforDiseaseModeling/dtk-tools-malaria/pull/77 to  close this.

**Comment by Sv3tlana** [comment]
This is done and merged. Closing.
