### ISSUE TITLE
Drug-campaign function arguments should match

### ISSUE THREAD

**Issue by edwenger** [InstituteforDiseaseModeling/dtk-tools-malaria#7]
The two reactive function calls got 3 new arguments recently:
https://github.com/InstituteforDiseaseModeling/dtk-tools-malaria/blob/master/malaria/interventions/malaria_drug_campaigns.py#L115

... but not the functions themselves:
https://github.com/InstituteforDiseaseModeling/dtk-tools-malaria/blob/master/malaria/interventions/malaria_drug_campaigns.py#L368

I'm not actually sure if that's a valid combo, but calling the top-level function with the reactive codes will throw a TypeError exception: add_rfMSAT() takes exactly 16 arguments (19 given).

**Comment by Sv3tlana** [comment]
Thanks for the catch. We decided not to update those functions, but I already updated their calls, but then forgot to fix that.

**Comment by Sv3tlana** [comment]
waiting for the PR

**Comment by jgerardin** [comment]
fixed in #6
