### ISSUE TITLE
PfHRP2, MalariaDiagnostics, AntimalarialDrug, and New Diagnostic Channels

### ISSUE THREAD

**Issue by Bridenbecker** [InstituteforDiseaseModeling/dtk-tools-malaria#8]
Per DtkTrunk ticket
https://github.com/InstituteforDiseaseModeling/DtkTrunk/issues/1926
we have made significant changes to the DTK:
- added a model of a new diagnostic, PfHRP2
- major changes to MalariaDiagnostics and AntimalarialDrug
- added several new channels to reports
- removed "New diagnostic"

Please note that the code has a few changes not stated in the ticket.

As of 12/8/2017, these changes are in a pending pull request:
https://github.com/InstituteforDiseaseModeling/DtkTrunk/pull/2009

**Comment by edwenger** [comment]
Many of the "add_malaria_drugs" functions will need to add a separate MalariaDiagnostic block to retain existing behavior.  That should be the first priority before we proceed with exploratory work to improve RDT model.
