### ISSUE TITLE
sahel- configure_sahel_intervention_system- update_vector_params- Capacity "doesn't take"

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/dtk-tools-malaria#84]
update_vector_params sets this:

>  "Capacity_Distribution_Over_Time": {

when this gets sent to COMPS, it becomes

> "Capacity_Distribution_Per_Year": {

**Comment by jgerardin** [comment]
This does not repro in my hands. I see "Capacity_Distribution_Over_Time" in COMPS. I'm up to date with both dtk-tools and dtk-tools-malaria.

**Comment by CWiswell-IDM** [comment]
This no longer reproduces for me, it looks like I had an old copy of this code somewhere related to a Python2.7 installation.
