### ISSUE TITLE
add_rfMSAT configuration should continue to give out drug events

### ISSUE THREAD

**Issue by edwenger** [InstituteforDiseaseModeling/dtk-tools-malaria#9]
Looks like the give out drug part got lost in recent update...

From @jgerardin 

> In add_rfMSAT() in malaria_drug_campaigns.py
> Around L409 if you’re on the dtk-tools-malaria version (or just above “for snowball in range(snowballs)” if not)
> Another call to add_diagnostic_survey() needs to be inserted
>  
>         add_diagnostic_survey(cb, coverage=coverage, start_day=start_day,
>                               diagnostic_type='Other', diagnostic_threshold=diagnostic_threshold, node_cfg=nodes,
>                               trigger_condition_list=[ snowball_setup[0]['Event_Trigger']],
>  event_name='Reactive MSAT level 0',
>                               positive_diagnosis_configs=event_config,
>                               IP_restrictions=ind_property_restrictions, NP_restrictions=node_property_restrictions,
>                               pos_diag_IP_restrictions=IP_restrictions)

**Comment by edwenger** [comment]
@jgerardin and @Sv3tlana 
Should this be closed now with the recent drug-related commits?

**Comment by jgerardin** [comment]
Yes, this is complete.

**Comment by Sv3tlana** [comment]
Thanks, @jgerardin !
