### ISSUE TITLE
CHW isn't working? created through health_seeking.py

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/dtk-tools-malaria#92]
https://comps2.idmod.org/#explore/Simulations?filters=ExperimentId=2ddb80dc-ddfc-e811-80ca-f0921c167866&offset=0&selectedId=2edb80dc-ddfc-e811-80ca-f0921c167866&layout=642C36&mode=list

login: <your username> or stitova
pass: Password123

In the experiment above, I am seeing the triggers for chw, but chw isn't doing anything about them. I'm not sure what's wrong. Investigation needed.

**Comment by jgerardin** [comment]
I can't login at the link.

**Comment by Sv3tlana** [comment]
added login info to the bug.

**Comment by Sv3tlana** [comment]
I will investigate

**Comment by jgerardin** [comment]
No one has used CHW in a long time. Totally possible something broke it in the last year and a half. Thanks for investigating!

**Comment by Sv3tlana** [comment]
The problem is  that dtk-tools-malaria has old code which uses "Distribution_Rate" parameter instead of "Max_Distributed_Per_Day" and there's no error and even though the default is MAX_INT for Max_Distributed_Per_Day, it for whatever reason just doesn't work? 

1) I will make an issue for this in dtktrunk and 
2) fix the dtk-tools-malaria chw parameters.

**Comment by Sv3tlana** [comment]
1 - https://github.com/InstituteforDiseaseModeling/DtkTrunk/issues/3052
2 - done, checked into master in dtk-tools-malaria
